import type { MeetingQuestion } from '../types'

/**
 * Mock Pacific Life Meeting 题库（13 题）。
 * keywords 为小写包含匹配；数值均出自 Food_CPI.ipynb / modelResults.ts。
 */
export const meetingQuestions: MeetingQuestion[] = [
  {
    id: 'q1',
    question: 'How exactly do you produce the 12-month forecast?',
    hintZh: '考察你能否完整讲出预测流水线：两个分项模型 → 各自 lag → 逐月预测 → 权重合并。',
    requiredTerms: ['lag', 'regression', 'expanding window', 'weights'],
    keyPoints: [
      { en: 'Food CPI is split into Food at Home and Food Away from Home, each with its own lead-lag regression.', zh: '先说明拆成两个分项，各有自己的 lead-lag regression', keywords: ['food at home', 'food away', 'two', 'split', 'component'] },
      { en: 'Home uses Processed Foods PPI (WPU02) with a 1-month lag; Away uses Leisure & Hospitality wages (CES7000000003) with a 12-month lag.', zh: '说出两个 predictor 与 lag（PPI lag 1；工资 lag 12）', keywords: ['ppi', 'wage', 'lag'] },
      { en: 'Coefficients are re-estimated at the current origin (June 2026) on all available history, then each of the 12 months gets its own forecast from its own required predictor month.', zh: '系数在当前 origin 重新估计；12 个月各自有对应的 predictor 月份', keywords: ['re-estimat', 'origin', 'each month', 'coefficient', 'estimate'] },
      { en: 'The two component forecasts are combined with relative-importance weights (8.188 / 5.260) into Total Food CPI.', zh: '用 relative importance 权重合并成 Total Food', keywords: ['weight', '8.188', '5.26', 'combine', 'relative importance'] },
    ],
    referenceAnswer: 'We split Food CPI into Food at Home and Food Away from Home. Each component has a lead-lag regression: Food at Home uses Processed Foods PPI with a 1-month lag, and Food Away uses Leisure & Hospitality wages with a 12-month lag. At the current forecast origin, June 2026, we re-estimate the coefficients on all available history. Then each of the next 12 months gets its own forecast from its own required predictor month. Finally we combine the two components into Total Food CPI using relative-importance weights of 8.188 and 5.260.',
    reviewModuleId: 'm9',
  },
  {
    id: 'q2',
    question: 'Are all twelve months based on observed predictor data?',
    hintZh: '陷阱题：答"是"就错了。必须区分 Home（只有第 1 个月 observed）与 Away（12 个月全部 observed）。',
    requiredTerms: ['observed', 'assumed', 'three-month average', 'lag'],
    keyPoints: [
      { en: 'No — it depends on the component.', zh: '先明确回答：不是全部', keywords: ['no', 'not all', 'depends'] },
      { en: 'For Food at Home (lag 1), only the July 2026 forecast uses an observed PPI value; the other 11 months use the latest three-month average assumption.', zh: 'Home 只有第 1 个月用 observed PPI，其余 11 个月用最新 3 个月平均假设', keywords: ['three-month', '3-month', 'average', 'assum'] },
      { en: 'For Food Away (lag 12), all 12 required wage months (July 2025 to June 2026) are already observed.', zh: 'Away 因 lag 12，12 个月所需工资全部已观察', keywords: ['all', 'observed', 'wage', '12-month', 'twelve'] },
      { en: 'The Forecast Input Audit table records the source of every input.', zh: '提到 audit 表逐行记录每个输入的来源', keywords: ['audit', 'input audit', 'table', 'record'] },
    ],
    referenceAnswer: 'No, not all of them. For Food at Home the lag is one month, so only the July 2026 forecast uses an observed PPI value. The other eleven months rely on an assumption: the latest three-month average of PPI growth. For Food Away from Home the lag is twelve months, so all twelve required wage observations, from July 2025 to June 2026, are already observed. Our Forecast Input Audit table records whether every single input is observed or assumed.',
    reviewModuleId: 'm9',
  },
  {
    id: 'q3',
    question: 'Which PPI value produces the July 2026 forecast?',
    hintZh: '具体数字题：lag 1 → 2026 年 6 月的 PPI YoY（1.63%），代入方程得到 2.47%。',
    requiredTerms: ['June 2026', 'lag', 'observed'],
    keyPoints: [
      { en: 'With a 1-month lag, the July 2026 forecast requires the June 2026 PPI value.', zh: '说明 lag 1 → 需要 2026 年 6 月的 PPI', keywords: ['june 2026', 'june', 'lag 1', 'one month'] },
      { en: 'That value is observed: Processed Foods PPI YoY = 1.63% (1.6294).', zh: '给出数值：1.63%（observed）', keywords: ['1.63', '1.6294', '1.6'] },
      { en: 'Plugging in: 1.408 + 0.650 × 1.63 ≈ 2.47% for Food at Home in July 2026.', zh: '能代入方程算出 ≈2.47%', keywords: ['2.47', '1.408', '0.65'] },
    ],
    referenceAnswer: 'Because the lag is one month, the July 2026 forecast uses the June 2026 value of the Processed Foods PPI, which is already observed. Its year-over-year growth is about 1.63 percent. Plugging into the current equation, 1.408 plus 0.650 times 1.63 gives about 2.47 percent for Food at Home in July 2026. This is the only month of the twelve that relies fully on an observed PPI value.',
    reviewModuleId: 'm9',
  },
  {
    id: 'q4',
    question: 'Why is the Food at Home lag now one month?',
    hintZh: '考察 lag 选择方法：≤1999 训练样本、0–12 扫描、Training R² 最高（0.769）。顺带说明与旧版 lag 3 的区别。',
    requiredTerms: ['lag', 'training', 'R-squared', '1999'],
    keyPoints: [
      { en: 'Lags from 0 to 12 months were scanned for each candidate predictor.', zh: '说明扫描了 0–12 个月的所有 lag', keywords: ['0 to 12', 'scan', 'every lag', 'all lag', '0-12'] },
      { en: 'Selection used only the lag-training sample through December 1999, to avoid look-ahead bias.', zh: '只用 ≤1999-12 的训练样本选择，防止 look-ahead', keywords: ['1999', 'training sample', 'look-ahead'] },
      { en: 'Lag 1 gave the highest training-sample R-squared for WPU02: 0.769.', zh: '给出依据：lag 1 的 Training R² 最高（0.769）', keywords: ['0.769', 'highest', 'r-squared', 'r2'] },
      { en: 'The lag was frozen before validation and the final test.', zh: '强调 lag 选定后冻结，之后不再改', keywords: ['frozen', 'freeze', 'fixed', 'before'] },
    ],
    referenceAnswer: 'We scanned every lag from 0 to 12 months for each candidate predictor, using only data through December 1999 — the lag-training sample. For the Processed Foods PPI, a one-month lag gave the highest training-sample R-squared, 0.769. That choice was frozen before the validation period and the 2016+ final test, so the lag was never tuned on test data. Economically it also makes sense: producer prices pass through to grocery shelves very quickly.',
    reviewModuleId: 'm4',
  },
  {
    id: 'q5',
    question: 'Why does the Food Away model use a 12-month lag?',
    hintZh: '考察对 Away legacy 模型的理解：延续性 + 12 个月预测全部基于 observed 工资数据。',
    requiredTerms: ['lag', 'wage', 'observed', 'continuity'],
    keyPoints: [
      { en: 'The primary Away model is the original all-employee wage model retained for continuity.', zh: '说明这是保留下来的原始模型（legacy，延续性）', keywords: ['original', 'continuity', 'legacy', 'retain'] },
      { en: 'Wage costs pass through to menu prices slowly, so a long lag is economically reasonable.', zh: '经济逻辑：工资成本传导到菜单价格较慢', keywords: ['slow', 'pass', 'menu', 'labor cost', 'gradually'] },
      { en: 'A practical benefit: with a 12-month lag, all twelve months of the current forecast use observed wage data — no assumptions needed.', zh: '实际好处：12 个月预测全部用 observed 工资', keywords: ['observed', 'all twelve', 'no assumption', '12 month'] },
    ],
    referenceAnswer: 'The primary Food Away model is the original all-employee wage model, retained for continuity. A 12-month lag is economically reasonable because restaurant labor costs pass through to menu prices slowly, through contracts and gradual repricing. It also has a practical benefit: with a 12-month lag, every one of the twelve forecast months uses wage data that is already observed, from July 2025 to June 2026, so the Away forecast requires no assumptions about future predictors.',
    reviewModuleId: 'm9',
  },
  {
    id: 'q6',
    question: 'Why did you separate training, validation and final test periods?',
    hintZh: '核心方法论题：三阶段各自的职责 + look-ahead bias 的考试比喻。',
    requiredTerms: ['look-ahead bias', 'training', 'validation', 'final test'],
    keyPoints: [
      { en: 'Choosing lags or models on the same data used for evaluation creates look-ahead bias and inflates performance.', zh: '说明动机：防止 look-ahead bias（先看答案再选模型）', keywords: ['look-ahead', 'bias', 'inflate', 'cheat', 'unfair'] },
      { en: 'Lags were chosen on data through 1999; models were compared on 2000–2015 outcomes; 2016+ was touched only for the final evaluation.', zh: '三阶段分工：≤1999 选 lag；2000–2015 比模型；2016+ 只做最终评估', keywords: ['1999', '2016', 'validation', '2000'] },
      { en: 'The final-test performance is honest because that data never influenced any selection.', zh: '强调 final test 数据从未参与任何选择，成绩才可信', keywords: ['never', 'honest', 'not used', 'unseen', 'credible'] },
    ],
    referenceAnswer: 'If we chose lags or picked models using the same data we later report performance on, we would be grading ourselves on an exam we had already seen — that is look-ahead bias, and it inflates results. So we split time into three roles. Lags were chosen only on data through 1999. Model comparison used forecast origins from 2000 to 2014, whose 12-month outcomes end in December 2015. The 2016-and-later data was used only once, for the final out-of-sample test, so its results are an honest measure.',
    reviewModuleId: 'm5',
  },
  {
    id: 'q7',
    question: 'What is an expanding-window regression?',
    hintZh: '定义 + 流程题：起点固定、终点随 origin 前移、每个 origin 重估系数、规格不变。',
    requiredTerms: ['expanding window', 'origin', 're-estimate', 'coefficients'],
    keyPoints: [
      { en: 'At each forecast origin, the model is re-estimated using all data available up to that month.', zh: '每个 origin 用「当时可得」的全部历史重估', keywords: ['re-estimat', 'available', 'up to', 'estimate'] },
      { en: 'The window start is fixed; the end expands forward as the origin moves.', zh: '起点固定、终点扩大（区别于 rolling/fixed）', keywords: ['expand', 'grows', 'start', 'fixed'] },
      { en: 'The specification (variables and lags) stays frozen; only coefficients update.', zh: '强调变量与 lag 冻结，只更新系数', keywords: ['specification', 'frozen', 'lag', 'only coefficient'] },
      { en: 'This simulates what a real-time forecaster could have done historically.', zh: '目的：模拟历史上实时预测者的处境', keywords: ['real-time', 'simulate', 'historical', 'would have'] },
    ],
    referenceAnswer: 'An expanding-window regression re-estimates the model at every forecast origin, using all the data available up to that month. The start of the training window is fixed, and the end expands forward as the origin moves — so the sample keeps growing. The specification, meaning the variables and lags, stays frozen; only the coefficients are updated. This simulates what a forecaster could actually have done in real time, which is what makes the backtest results meaningful.',
    reviewModuleId: 'm8',
  },
  {
    id: 'q8',
    question: 'What does an OOS R² of 0.598 mean?',
    hintZh: '最容易答错的题：必须相对 no-change benchmark 解释，并明确否认"59.8% 准确率"。',
    requiredTerms: ['no-change benchmark', 'squared errors', 'out-of-sample'],
    keyPoints: [
      { en: 'It compares the model against a no-change benchmark that simply repeats the latest Food CPI YoY rate.', zh: '说明比较对象是 no-change benchmark', keywords: ['no-change', 'benchmark', 'naive', 'random walk'] },
      { en: 'It means the model reduced out-of-sample squared forecast errors by about 59.8% relative to that benchmark.', zh: '正确解读：样本外平方误差比基准低约 59.8%', keywords: ['59.8', 'reduc', 'squared error', 'lower'] },
      { en: 'It is NOT a 59.8% forecast accuracy rate.', zh: '明确否认"准确率"误读', keywords: ['not', 'accuracy'] },
    ],
    referenceAnswer: 'OOS R-squared is always measured against a no-change benchmark — a naive forecast that just repeats the latest observed Food CPI year-over-year rate. A value of 0.598 means our model\'s sum of squared out-of-sample errors is about 59.8 percent lower than the benchmark\'s. It does not mean the model is "59.8 percent accurate". A positive value simply says we beat the naive forecast; zero would mean no improvement, and negative would mean we did worse.',
    reviewModuleId: 'm11',
  },
  {
    id: 'q9',
    question: 'Why not choose the survey model just because its OOS R² is higher?',
    hintZh: '模型选择哲学题：0.636 vs 0.598 的差距 vs 区域性调查的解释性代价。',
    requiredTerms: ['regional', 'sensitivity', 'transparent', 'national'],
    keyPoints: [
      { en: 'The survey model\'s 12-month OOS R² (0.636) is only modestly higher than the primary\'s (0.598).', zh: '承认差距存在但有限（0.636 vs 0.598）', keywords: ['0.636', '0.598', 'modest', 'small', 'slightly'] },
      { en: 'The Philadelphia Fed survey is regional and not food-industry-specific, so it is harder to defend economically.', zh: '关键理由：Philly 调查是区域性、非食品专属', keywords: ['regional', 'philadelphia', 'not food', 'manufacturing'] },
      { en: 'The primary baseline uses national, food-channel inputs and is more transparent and explainable.', zh: 'Primary 用全国性食品链指标，更透明可解释', keywords: ['national', 'transparent', 'explain', 'defend'] },
      { en: 'So the survey model is reported as a sensitivity scenario, not as the primary forecast.', zh: '结论：Survey 作为敏感性情景保留，不替代主预测', keywords: ['sensitivity', 'scenario', 'not primary', 'alternative'] },
    ],
    referenceAnswer: 'The survey model\'s out-of-sample R-squared, 0.636, is only modestly higher than the primary baseline\'s 0.598. In exchange, it depends on the Philadelphia Fed survey, which is regional and not specific to the food industry, so it is much harder to defend economically to stakeholders. The primary baseline uses national, food-channel inputs — the Processed Foods PPI and national hospitality wages — and is transparent and easy to explain. A slightly better backtest number does not outweigh that, so we keep the survey model as a sensitivity scenario rather than the primary forecast.',
    reviewModuleId: 'm7',
  },
  {
    id: 'q10',
    question: 'How confident are you in the 3.02% forecast?',
    hintZh: '不确定性题：用 RMSE（2.035 pp）、经验区间、以及"后 11 个月是假设情景"来回答，不吹不贬。',
    requiredTerms: ['RMSE', 'interval', 'assumption', 'uncertainty'],
    keyPoints: [
      { en: 'Historical 12-month-ahead OOS RMSE is about 2.0 percentage points, so uncertainty is substantial.', zh: '用 12M OOS RMSE ≈ 2.035 pp 说明不确定性量级', keywords: ['2.0', 'rmse', '2.035'] },
      { en: 'The empirical 95% interval for June 2027 is roughly −0.6% to 8.2%, built from actual past forecast errors.', zh: '给出经验区间（约 −0.6% 到 8.2%）', keywords: ['interval', '-0.6', '8.2', 'empirical'] },
      { en: 'Months beyond the first rely on the three-month-average PPI assumption, so 3.02% is a baseline scenario.', zh: '提醒：后面月份依赖 PPI 假设，3.02% 是基准情景', keywords: ['assum', 'scenario', 'baseline', 'three-month'] },
      { en: 'The model beats the no-change benchmark (OOS R² 0.598), which is the right standard of confidence.', zh: '正面证据：稳定优于 no-change（0.598）', keywords: ['0.598', 'no-change', 'beat', 'benchmark'] },
    ],
    referenceAnswer: 'We hold it as a well-tested central scenario, not a precise promise. Historically, our 12-month-ahead out-of-sample RMSE is about 2 percentage points, and the empirical 95 percent interval around the June 2027 forecast runs from roughly minus 0.6 to plus 8.2 percent — food inflation is volatile. Also, months beyond the first rely on a three-month-average PPI assumption, so 3.02 percent is a baseline scenario. What supports confidence is that the model consistently beats the no-change benchmark, with an OOS R-squared of 0.598.',
    reviewModuleId: 'm11',
  },
  {
    id: 'q11',
    question: 'Why is the survey scenario 4.34%?',
    hintZh: '机制题：费城联储未来售价指数目前处于高位 → 通过正系数推高预测 → higher-inflation scenario。',
    requiredTerms: ['survey', 'price intentions', 'scenario', 'Philadelphia'],
    keyPoints: [
      { en: 'The survey models add the Philadelphia Fed future prices received index, which measures firms\' selling-price intentions.', zh: '说明加入了什么：Philly 未来售价意向指数', keywords: ['philadelphia', 'philly', 'prices received', 'intention'] },
      { en: 'Recent survey readings are elevated (e.g. 67.2 in June 2026), and they enter with positive coefficients.', zh: '当前调查读数处于高位，通过正系数推高预测', keywords: ['elevated', 'high', '67', 'positive', 'push'] },
      { en: 'So the survey forecast (4.34%) answers: if these price intentions pass through, food inflation would be higher.', zh: '4.34% 回答的问题：如果价格意向传导，通胀会更高', keywords: ['4.34', 'pass through', 'higher', 'if'] },
      { en: 'It is a sensitivity scenario, not the primary forecast, because the survey is regional and not food-specific.', zh: '重申定位：敏感性情景，非主预测', keywords: ['sensitivity', 'not the primary', 'regional', 'scenario'] },
    ],
    referenceAnswer: 'The survey models add the Philadelphia Fed future prices received index, which captures firms\' selling-price intentions over the next six months. Recent readings are elevated — for example 67.2 in June 2026 — and the index enters both survey equations with positive coefficients, so it pushes the forecast up to 4.34 percent by June 2027. That number answers a specific question: if these business price intentions actually pass through to food prices, inflation would be meaningfully higher. Because the survey is regional and not food-specific, we report this as a higher-inflation sensitivity scenario, not as the primary forecast.',
    reviewModuleId: 'm7',
  },
  {
    id: 'q12',
    question: 'What are the main model limitations?',
    hintZh: '至少讲出六项限制中的四项，并能说明它们为什么不致命。',
    requiredTerms: ['vintage', 'assumption', 'regional', 'serial correlation'],
    keyPoints: [
      { en: 'The backtest uses today\'s revised FRED data, not real-time ALFRED vintages, and release-day timing is not reconstructed.', zh: '伪实时回测：修订后数据 + 未重建发布日历', keywords: ['revised', 'vintage', 'alfred', 'release'] },
      { en: 'Unobserved future predictors use a three-month average, so later months are baseline scenarios.', zh: '未来 predictor 用 3 个月平均假设', keywords: ['three-month', 'average', 'assum'] },
      { en: 'Current relative-importance weights are applied to history; surveys are regional, not food-specific.', zh: '历史组合用当前权重；调查是区域性的', keywords: ['weight', 'regional', 'current'] },
      { en: 'Overlapping 12-month errors are serially correlated; HAC standard errors and empirical intervals address this.', zh: '重叠误差序列相关（HAC SE、经验区间应对）', keywords: ['overlap', 'serial', 'correlat', 'hac'] },
    ],
    referenceAnswer: 'Six main ones. First, the backtest uses today\'s revised FRED data, not real-time ALFRED vintages. Second, we do not reconstruct exact historical release days. Third, unobserved future predictors use a latest three-month average, so later forecast months are baseline scenarios. Fourth, we apply current relative-importance weights to historical combinations. Fifth, the Philadelphia and Dallas surveys are regional, not food-specific — they are sensitivity indicators. Sixth, overlapping 12-month forecast errors are serially correlated, which is why we use HAC standard errors and rely on empirical error intervals as the main reliability measure.',
    reviewModuleId: 'm13',
  },
  {
    id: 'q13',
    question: 'How is Food CPI converted into a Headline CPI contribution?',
    hintZh: '公式题：Total Food YoY × 13.447 / 100，给出 0.41 pp 的例子。',
    requiredTerms: ['relative importance', 'contribution', '13.447'],
    keyPoints: [
      { en: 'Total Food CPI has a relative importance of 13.447% in the headline index.', zh: '说出权重：13.447%', keywords: ['13.447', '13.4'] },
      { en: 'Contribution = Food CPI YoY forecast × 13.447 / 100.', zh: '给出公式：Food YoY × 13.447 / 100', keywords: ['multiply', 'times', '/ 100', 'x 13', '× 13'] },
      { en: 'Example: 3.02% × 0.13447 ≈ 0.41 percentage points of headline inflation.', zh: '举例：3.02% → ≈0.41 pp', keywords: ['0.41', '3.02', 'percentage point'] },
      { en: 'This plugs into the team\'s bottom-up sum across components.', zh: '说明它如何进入团队的 bottom-up 加总', keywords: ['bottom-up', 'sum', 'team', 'component'] },
    ],
    referenceAnswer: 'Total Food has a relative importance of 13.447 percent in the headline CPI. So the contribution is simply the Food CPI year-over-year forecast times 13.447 divided by 100. For example, our June 2027 primary forecast of 3.02 percent translates into about 0.41 percentage points of headline inflation. That number is what plugs into the team\'s bottom-up aggregation, where every component\'s contribution is summed to build the headline CPI forecast.',
    reviewModuleId: 'm10',
  },
]
