import type { WalkthroughCell } from '../types'

/**
 * Notebook Walkthrough：45 个 cell（index 0–44）逐格讲解。
 * 严格对应 "Food CPI Forecast — Long-History and Survey-Enhanced Version"。
 */
export const walkthroughCells: WalkthroughCell[] = [
  {
    index: 0,
    cellType: 'markdown',
    section: 'Overview',
    title: '标题与全景：这个 Notebook 要做什么',
    whatItDoes: '宣布 Notebook 的六大改进：延长历史样本、增加农业/能源/工资/调查指标、调查指数保持 level、分离三个样本阶段、对比国家级 baseline 与调查增强模型、给出每个预测月的 predictor 来源。并明确 Primary forecast（PPI + 全体员工工资）与 Survey sensitivity 的分工。',
    whyNeeded: '开篇立规矩：读者从第一屏就知道主预测是什么、调查模型只是敏感性分析——防止后面 4.34% 被误当成主预测。',
    linkToForecast: '这里定义的 Primary/Survey 二分法，就是最终 3.02% vs 4.34% 两个数字的来源框架。',
  },
  {
    index: 1,
    cellType: 'markdown',
    section: '1. What the model is doing — in plain language',
    title: '白话版模型说明',
    whatItDoes: '用平实语言解释：Food CPI 拆成两个分项（杂货跟供应链成本、餐饮跟劳动力成本）；lead-lag regression 就是把 predictor 往回挪 L 个月的普通回归：FoodCPI(t) = α + β·X(t−L) + ε；expanding-window backtest 回答"如果历史上每个月都用这个模型，误差会有多大"。',
    whyNeeded: '给零基础读者（以及会议上的非技术听众）一个不依赖公式的心智模型。',
    linkToForecast: '这三句话就是整个方法论的浓缩——后面的一切代码都是在实现它们。',
  },
  {
    index: 2,
    cellType: 'markdown',
    section: '2. Import the packages',
    title: '第 2 章标题：导入工具包',
    whatItDoes: '章节标题，引出下一格的 import。',
    whyNeeded: '保持 Notebook 章节结构清晰。',
  },
  {
    index: 3,
    cellType: 'code',
    section: '2. Import the packages',
    title: '导入 pandas / numpy / statsmodels 等',
    code: 'import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport statsmodels.api as sm\nfrom pandas_datareader import data as web',
    whatItDoes: '导入数据处理（pandas/numpy）、画图（matplotlib）、回归（statsmodels）和 FRED 下载（pandas_datareader）工具。',
    whyNeeded: '后面所有 cell 依赖这些库：sm.OLS 做回归、web.DataReader 下载 FRED 数据。',
    inputs: '无（纯导入）',
    outputs: '可用的库命名空间',
    ifBroken: '删掉任何一行，后面用到该库的 cell 会立刻 NameError——例如没有 statsmodels 就无法估计任何回归。',
  },
  {
    index: 4,
    cellType: 'markdown',
    section: '3. Dates, model periods, and CPI weights',
    title: '三个日期区间的分工说明',
    whatItDoes: '解释日期的三种职责：Lag-training（到 1999 年，选 lag）；Validation（origins 2000–2014，12 个月预测最晚 2015-12 实现，比较模型）；Final test（origins 2016 起，评估最终表现）。',
    whyNeeded: '这是防止 Look-ahead Bias 的设计蓝图——每段数据只能承担一种职责。',
    linkToForecast: '正因为 2016+ 从未参与选择，最终报告的 RMSE 2.035 / OOS R² 0.598 才可信。',
  },
  {
    index: 5,
    cellType: 'code',
    section: '3. Dates, model periods, and CPI weights',
    title: '定义时间常量与 CPI 权重',
    code: 'LAG_TRAIN_END = pd.Timestamp("1999-12-01")\nVALIDATION_FIRST_ORIGIN = pd.Timestamp("2000-01-01")\nVALIDATION_LAST_ORIGIN = pd.Timestamp("2014-12-01")\nFINAL_TEST_FIRST_ORIGIN = pd.Timestamp("2016-01-01")\nFORECAST_HORIZON = 12\nMIN_TRAINING_OBSERVATIONS = 60\n\nFOOD_AT_HOME_RELATIVE_IMPORTANCE = 8.188\nFOOD_AWAY_RELATIVE_IMPORTANCE = 5.260\nTOTAL_FOOD_RELATIVE_IMPORTANCE = 13.447\nHOME_WEIGHT_INSIDE_FOOD = 8.188 / (8.188 + 5.260)',
    whatItDoes: '把所有时间边界（1999-12 / 2000-01 / 2014-12 / 2016-01）、预测长度（12 个月）、最少训练观测（60）与 CPI 相对重要性权重（8.188 / 5.260 / 13.447）定义为常量。',
    whyNeeded: '集中定义、全文引用：想改边界只需改这里，且保证每个 cell 用的是同一套规则。',
    inputs: '2026 年 6 月 CPI 发布中的 relative importance（2026 年 5 月值）',
    outputs: '全局常量',
    ifBroken: '改错 LAG_TRAIN_END（比如写成 2016）会让 lag 选择"看到"验证与测试数据，整个防 look-ahead 设计崩塌。',
    linkToForecast: 'HOME_WEIGHT_INSIDE_FOOD ≈ 0.609 直接决定 Total Food 组合与 3.02% 的计算。',
  },
  {
    index: 6,
    cellType: 'markdown',
    section: '4. Data dictionary',
    title: '数据字典的阅读说明',
    whatItDoes: '解释 transform 两种取值：yoy_pct（12 个月百分比变化）与 level（扩散指数按发布值使用，不能做 pct_change(12)）。并说明 Bloomberg/ISM、S&P Global 因专有或无稳定 FRED 历史而不用，改用公开的费城/达拉斯联储调查。',
    whyNeeded: '一句话讲清本项目最容易犯的转换错误（对 diffusion index 求 YoY）以及数据选择的透明性原则。',
  },
  {
    index: 7,
    cellType: 'code',
    section: '4. Data dictionary',
    title: '18 个序列的元数据表',
    code: 'series_metadata = pd.DataFrame([\n  ["food_total_cpi", "CPIUFDSL", "Total Food CPI", "target", "yoy_pct", ...],\n  ["ppi_processed_foods", "WPU02", ..., "Primary Food at Home predictor"],\n  ["wage_leisure_hospitality_all", "CES7000000003", ..., "Primary Food Away predictor; starts 2006"],\n  ...  # 共 18 行\n], columns=["Variable", "FRED_series", "Label", "Channel", "Transform", "Model_role"])',
    outputSummary: '18 行元数据表：3 个 CPI 目标、多个 PPI/农业/能源/进口/工资序列、3 个联储调查（level）。',
    whatItDoes: '为每个序列登记：变量名、FRED ID、含义、所属通道、转换规则、模型角色。同时生成 series 与 transform_rules 两个查询字典。',
    whyNeeded: '单一事实来源：下载、转换、建模全部按这张表执行，杜绝"某个序列悄悄用了错误转换"。',
    inputs: '手工整理的 18 个 FRED 序列信息',
    outputs: 'series_metadata 表 + series / transform_rules 字典',
    ifBroken: '把 philly 调查的 transform 误写成 yoy_pct，调查模型的输入会变成无意义的数字，Survey Sensitivity 全部失真。',
  },
  {
    index: 8,
    cellType: 'markdown',
    section: '5. Load and validate the monthly data',
    title: '加载策略：先 FRED、后 CSV 备份',
    whatItDoes: '说明先尝试 FRED 实时下载，失败则读取随附的 Food_CPI_Data.csv 备份（含全部 18 个序列的完整历史）。',
    whyNeeded: '可复现性：没有网络时 Notebook 仍能完整运行，数据版本也有据可查。',
  },
  {
    index: 9,
    cellType: 'code',
    section: '5. Load and validate the monthly data',
    title: '下载/读取数据 + 新鲜度检查表',
    code: 'downloaded = pd.concat({v: web.DataReader(fred_id, "fred", DATA_START, DATA_AS_OF)[fred_id]\n                        for v, fred_id in series.items()}, axis=1)\nif latest_nonmissing_month(downloaded)["food_total_cpi"] < EXPECTED_CPI_LATEST:\n    raise ValueError("The live CPI download is older than June 2026.")\n...\nmonthly_index = pd.date_range(data.index.min(), data.index.max(), freq="MS")\ndata = data.reindex(monthly_index)',
    outputSummary: 'Data source: Live FRED download；freshness 表显示每个序列的首末观测（如 WPU01 从 1913-01 起、CPI 目标到 2026-06、费城调查到 2026-07）。',
    whatItDoes: '下载 18 个序列，校验 CPI 至少更新到 2026-06（否则退回 CSV 备份），把索引补成完整的月度日历，并打印每个序列的首个/最新观测与缺失统计。',
    whyNeeded: '完整月历保证 shift(1) 恒等于 1 个日历月；新鲜度表让"数据到几月"一目了然——会议上第一时间能回答。',
    inputs: 'FRED API 或 Food_CPI_Data.csv',
    outputs: 'data（1362 个月 × 18 列）+ freshness 表',
    ifBroken: '去掉 reindex，缺失月份会被静默压缩，lag 对齐就会错位——lag 1 可能实际隔了 2 个月。',
    linkToForecast: '这里确认的 2026-06 最新 CPI 就是当前 forecast origin。',
  },
  {
    index: 10,
    cellType: 'markdown',
    section: '5. Load and validate the monthly data',
    title: '5.1 数据质量检查的原则',
    whatItDoes: '说明月历保持完整、缺失目标值（如 2025 年 10 月停摆导致的 CPI 缺失）保持缺失、绝不发明数据。',
    whyNeeded: '诚实原则：缺的数据就是缺的——插值出来的"数据"会污染训练与评估。',
  },
  {
    index: 11,
    cellType: 'code',
    section: '5. Load and validate the monthly data',
    title: '断言检查：索引完整性与已知缺口',
    code: 'assert not data.index.has_duplicates\nassert data.index.equals(pd.date_range(data.index.min(), data.index.max(), freq="MS"))\nassert data["food_at_home_cpi"].first_valid_index() == pd.Timestamp("1952-01-01")\nassert pd.isna(data.loc[pd.Timestamp("2025-10-01"), "food_at_home_cpi"])',
    outputSummary: '展示 2025-01 之后仍含缺失的行：2025-10（CPI 三个目标缺失）与 2026-07（多数序列未发布，仅调查已出）。',
    whatItDoes: '用 assert 固化关键事实：索引无重复且连续；各 CPI 序列起点正确；2025-10 的 CPI 确实缺失（联邦停摆）。',
    whyNeeded: '把"我以为的数据形状"变成"被验证过的数据形状"——数据源哪天悄悄变了，Notebook 会立刻报错而不是继续算错。',
    inputs: 'data',
    outputs: '通过断言 + 缺失行展示',
    ifBroken: '删掉这些 assert，数据源变化（如序列改版）会静默进入模型，产出无法解释的预测。',
  },
  {
    index: 12,
    cellType: 'markdown',
    section: '6. Transform each variable correctly',
    title: '转换规则说明',
    whatItDoes: '说明价格/工资类序列转为 YoY 增长率，调查扩散指数保持 level；结果表叫 model_data（因为并非每列都是增长率）。',
    whyNeeded: '再次强调本项目的核心数据纪律：不同性质的序列用不同转换。',
  },
  {
    index: 13,
    cellType: 'code',
    section: '6. Transform each variable correctly',
    title: '执行转换：yoy_pct 或 level',
    code: 'for variable, rule in transform_rules.items():\n    if rule == "yoy_pct":\n        model_data[variable] = data[variable].pct_change(periods=12, fill_method=None) * 100\n    elif rule == "level":\n        model_data[variable] = data[variable]\n\nassert not np.isinf(model_data.select_dtypes(include=[np.number])).any().any()',
    outputSummary: 'model_data 尾部：2026-06 的 food_at_home 2.704、food_away 3.366、food_total 2.987、ppi_processed 1.629、wage_all 3.870；philly 调查保持 53.2 / 67.2 等 level 值。',
    whatItDoes: '按数据字典规则批量转换：pct_change(12)×100 得到 YoY%；调查列原样保留；断言无 Inf。',
    whyNeeded: 'CPI 指数水平不可比（349.6 是什么意思？），YoY 才是"通胀率"；扩散指数是净差额，做 YoY 在概念上是错的。',
    inputs: 'data + transform_rules',
    outputs: 'model_data（模型的直接输入）',
    ifBroken: '把 periods=12 写成 1 会变成 MoM 增速，所有回归、lag 选择、预测全部错位。',
    linkToForecast: '2026-06 的 ppi_processed 1.6294 就是 2026-07 预测（h=1）的直接输入。',
  },
  {
    index: 14,
    cellType: 'markdown',
    section: '6. Transform each variable correctly',
    title: '6.1 为什么长历史很重要',
    whatItDoes: '引出下一格的图：新版本样本远早于 2000 年。',
    whyNeeded: '回应会议反馈——旧版只有 2000 年后的数据，lag 选择与验证挤在同一段时间。',
  },
  {
    index: 15,
    cellType: 'code',
    section: '6. Transform each variable correctly',
    title: '画图：Food CPI 历史延伸到 2000 年之前',
    code: 'plt.plot(model_data.index, model_data["food_at_home_cpi"], label="Food at Home YoY")\nplt.plot(model_data.index, model_data["food_away_cpi"], label="Food Away from Home YoY")\nplt.axvline(pd.Timestamp("2000-01-01"), ..., label="Old notebook start")',
    outputSummary: '一张长历史折线图：两个分项 YoY 从 1950 年代延伸至 2026 年，灰色虚线标出旧 Notebook 的 2000 年起点。',
    whatItDoes: '可视化对比新旧样本范围：70 年代的高通胀、90 年代的低通胀、2022 年的食品通胀高峰全部进入视野。',
    whyNeeded: '长历史让 lag-training（≤1999）拥有独立的完整样本，这是三阶段设计的前提。',
    inputs: 'model_data 两列',
    outputs: 'matplotlib 图',
    linkToForecast: '网站 Module 1 的 foodHistory 图就是它的复刻。',
  },
  {
    index: 16,
    cellType: 'markdown',
    section: '7. Choose lags using only data through 1999',
    title: 'Lag 选择规则声明',
    whatItDoes: '声明：对每个长历史候选指标测试 lag 0–12，用 training-sample R² 最高者，且在进入 2000–2015 验证和 2016+ 测试之前冻结。特别指出"看完测试结果再选 lag"是不公平的。',
    whyNeeded: '这是 Look-ahead Bias 防线的第一环，也是回答"为什么 lag 是 1 不是 3"的依据。',
  },
  {
    index: 17,
    cellType: 'code',
    section: '7. Choose lags using only data through 1999',
    title: '0–12 lag 扫描与最优 lag 冻结',
    code: 'def scan_univariate_lags(frame, target, predictors, sample_end, max_lag=12, min_obs=60):\n    for predictor in predictors:\n        for lag in range(max_lag + 1):\n            pair = pd.DataFrame({"target": frame[target],\n                                 "predictor": frame[predictor].shift(lag)}).loc[:sample_end].dropna()\n            fitted = sm.OLS(pair["target"], sm.add_constant(pair["predictor"])).fit()\n            ...\nhome_lag_scan = scan_univariate_lags(model_data, "food_at_home_cpi", home_long_history_predictors, LAG_TRAIN_END)',
    outputSummary: 'Home 最优 lag 表：ppi_processed_foods lag 1（R² 0.769）、ppi_finished_consumer_foods lag 1（0.875）、farm lag 2、energy lag 0……Away 表：philly future lag 2（0.587）、wage production lag 2（0.476）等。',
    whatItDoes: '对每个候选 predictor × 每个 lag（0–12）拟合一元回归（样本截至 1999-12，min_obs=60），记录 R²，按 predictor 取最优 lag 存入 home_lag_lookup / away_lag_lookup。',
    whyNeeded: '用同一把尺子（Training R²）客观选 lag，并把选择过程完全限制在 1999 年之前。',
    inputs: 'model_data、候选 predictor 列表、LAG_TRAIN_END',
    outputs: 'home_best_lags / away_best_lags 表与 lag 查询字典',
    ifBroken: '把 sample_end 去掉（用全样本选 lag），2016+ 测试的成绩会被 look-ahead 污染，无法作为诚实证据。',
    linkToForecast: 'WPU02 在这里选出 lag=1——这正是"2026-07 预测用 2026-06 PPI"的出处。',
  },
  {
    index: 18,
    cellType: 'markdown',
    section: '8. Freeze the model specifications before the final test',
    title: '模型规范冻结与"小模型"哲学',
    whatItDoes: '说明主规格刻意保持精简：把所有相关的食品/商品指数塞进一个方程会造成 multicollinearity 和 overfitting。列出四类：Primary baseline、Long-history baseline、Survey-expanded sensitivity（费城调查是区域性、非食品专属）、其他 robustness checks。',
    whyNeeded: '回答"为什么不用更多变量"：变量多≠更好，可解释与稳健才是目标。',
  },
  {
    index: 19,
    cellType: 'code',
    section: '8. Freeze the model specifications before the final test',
    title: '定义 9 个模型规格',
    code: 'model_specs = {\n  "Home baseline": {"predictors": {"ppi_processed_foods": home_lag_lookup["ppi_processed_foods"]}, ...},\n  "Home survey expanded": {"predictors": {"ppi_processed_foods": 1, "philly_future_prices_received": 0}, ...},\n  ...\n  "Away legacy all-employee": {"predictors": {"wage_leisure_hospitality_all": 12},\n                               "role": "Original model retained for continuity"},\n}',
    outputSummary: '9 行模型清单：5 个 Home 模型 + 4 个 Away 模型，各自的 predictor(lag) 与角色。',
    whatItDoes: '把每个模型的目标、predictor 与 lag 写成固定的字典。Away legacy 的 lag 12 是直接指定的（原始模型延续），其余 lag 来自 Cell 17 的冻结结果。',
    whyNeeded: '规范一旦写死，后面的验证与测试只能"评估"它们，不能再改——这是冻结的技术形式。',
    inputs: 'home_lag_lookup / away_lag_lookup',
    outputs: 'model_specs 字典 + model_spec_table 展示表',
    ifBroken: '在看完 2016+ 结果后回来改这里的 lag，就等于重新打开了已封存的考卷。',
    linkToForecast: '其中 Home baseline 与 Away legacy all-employee 就是产出 3.02% 的两个 Primary 组件。',
  },
  {
    index: 20,
    cellType: 'markdown',
    section: '9. General expanding-window forecast engine',
    title: '预测引擎的设计说明',
    whatItDoes: '说明每个 forecast origin 上系数用"截至该月"的数据重估、lag 与变量固定；未来 predictor 若未观察则用最新 3 个月平均，且每个决定都记入 audit 表。',
    whyNeeded: '一台引擎同时服务历史回测与当前预测，规则完全一致。',
  },
  {
    index: 21,
    cellType: 'code',
    section: '9. General expanding-window forecast engine',
    title: '核心函数：forecast_from_origin 与 expanding_window_backtest',
    code: 'def forecast_from_origin(frame, model_name, spec, origin, horizon=12, information_cutoffs=None, ...):\n    train = ...  # 目标 + 各 predictor.shift(lag)，截至 origin，dropna\n    model = sm.OLS(train["y"], x_train).fit(cov_type="HAC", cov_kwds={"maxlags": 12})\n    for h in range(1, horizon + 1):\n        predictor_date = target_date - pd.DateOffset(months=lag)\n        known = predictor_date <= cutoff and notna(...)\n        value = frame.loc[predictor_date, p] if known else frame.loc[:cutoff, p].dropna().tail(3).mean()\n        ...  # 记录 forecast 行 + audit 行 + 系数行',
    outputSummary: '定义两个函数，无直接输出。',
    whatItDoes: '单个 origin：构造训练集（按 lag 平移 predictor）→ HAC-OLS 估计 → 逐月（h=1..12）确定所需 predictor 月份，Observed 用真实值、未观察用最新 3 个月平均 → 输出预测、audit、系数三张表。expanding_window_backtest 对一段 origins 循环调用。',
    whyNeeded: '这是整个 Notebook 的心脏：回测、当前预测、audit 表、系数表全部由它产出，保证规则统一。',
    inputs: 'model_data、模型规格、origin、information_cutoffs',
    outputs: 'forecast / audit / coefficient 三个 DataFrame',
    ifBroken: '把 known 的判断去掉（总是用真实值），未来月份会"偷看"尚未发布的 predictor——历史回测立即变成作弊。',
    linkToForecast: '当前 12 个月预测（Cell 35）与全部历史回测都直接调用它。',
  },
  {
    index: 22,
    cellType: 'markdown',
    section: '10. Pre-2016 model validation',
    title: '验证期设计说明',
    whatItDoes: '说明验证 origins 从 2000-01 到 2014-12，12 个月结果最晚在 2015-12 实现——整个模型比较完全停在 2016 之前。',
    whyNeeded: '在打开 Final Test 之前完成 Baseline vs Expanded 的比较，2016+ 保持"未拆封"。',
  },
  {
    index: 23,
    cellType: 'code',
    section: '10. Pre-2016 model validation',
    title: '运行验证回测并计算 OOS 指标',
    code: 'validation_backtests = {name: expanding_window_backtest(model_data, name, model_specs[name],\n    VALIDATION_FIRST_ORIGIN, VALIDATION_LAST_ORIGIN) for name in validation_models}\n\ndef calculate_oos_metrics(backtest):\n    errors = result["Actual"] - result["Forecast"]\n    benchmark_errors = result["Actual"] - result["No_change_benchmark"]\n    return pd.Series({"OOS_RMSE": ..., "OOS_MAE": ...,\n        "OOS_R_squared_vs_no_change": 1 - sum(errors**2)/sum(benchmark_errors**2), ...})',
    outputSummary: '验证对比表（12-month ahead，180 个预测）：Away survey expanded RMSE 0.566 最佳；Home 侧 global-food 2.322 最佳，Home baseline 3.442。',
    whatItDoes: '对 8 个模型跑 2000–2014 的 expanding-window 回测，并定义贯穿全文的指标函数：RMSE、MAE、平均误差、相对 no-change 的 OOS R²、名义区间覆盖率。',
    whyNeeded: 'calculate_oos_metrics 是所有"成绩"的统一算法——验证、测试、组合都用它，保证可比。',
    inputs: 'model_data + model_specs + 验证期边界',
    outputs: 'validation_backtests + validation_comparison 表',
    ifBroken: '若把 No_change_benchmark 从 origin 的值改成别的，OOS R² 的含义就变了——0.598 的解释全部失效。',
  },
  {
    index: 24,
    cellType: 'markdown',
    section: '10. Pre-2016 model validation',
    title: '10.1 验证结果怎么读',
    whatItDoes: '强调调查指标不能只凭 in-sample R² 提升被接受，必须在验证期降低 12 个月 RMSE；表现不佳的农业/能源模型也保持可见。',
    whyNeeded: '模型对比的标准是样本外预测误差，不是拟合优度——并且诚实展示所有结果。',
  },
  {
    index: 25,
    cellType: 'code',
    section: '10. Pre-2016 model validation',
    title: '打印每个分项的验证最优模型',
    code: 'for component in ["Food at Home", "Food Away from Home"]:\n    best_row = subset.sort_values("OOS_RMSE").iloc[0]\n    print(f"Best pre-2016 validation model for {component}: ...")',
    outputSummary: 'Food at Home 最佳：Home global-food（RMSE 2.322）；Food Away 最佳：Away survey expanded（RMSE 0.566）。',
    whatItDoes: '从验证表中挑出每个分项 RMSE 最低的模型并打印。',
    whyNeeded: '给验证阶段一个明确结论；也说明最终 Primary 的选择还要综合全国代表性与可解释性（不是"验证第一名自动当选"）。',
    inputs: 'validation_comparison',
    outputs: '两行 print',
  },
  {
    index: 26,
    cellType: 'markdown',
    section: '11. Final 2016+ out-of-sample test',
    title: 'Final Test 规则声明',
    whatItDoes: '声明从 2016-01 origins 起评估固定规格；2016+ 从未用于选 lag 或选模型。',
    whyNeeded: '定义"这张成绩单为什么可信"。',
  },
  {
    index: 27,
    cellType: 'code',
    section: '11. Final 2016+ out-of-sample test',
    title: '运行 2016+ 最终测试',
    code: 'final_test_last_origin = latest_target_month - pd.DateOffset(months=FORECAST_HORIZON)\nfinal_test_backtests = {name: expanding_window_backtest(model_data, name, model_specs[name],\n    FINAL_TEST_FIRST_ORIGIN, final_test_last_origin) for name in final_test_models}',
    outputSummary: '最终测试表（12M ahead，113 个预测）：Home baseline RMSE 2.797 / OOS R² 0.600；Away legacy 1.610 / 0.097；Away survey 1.464 / 0.254；Home survey 2.698 / 0.628。',
    whatItDoes: '对 7 个模型跑 2016-01 至最后可评估 origin（最新目标月往前推 12 个月）的回测，汇总 12-month-ahead 指标。',
    whyNeeded: '这是给 Pacific Life 看的核心证据：固定规格在完全未参与选择的 9 年多数据上的真实表现。',
    inputs: 'model_data + 冻结的 model_specs',
    outputs: 'final_test_backtests + final_test_comparison 表',
    linkToForecast: '网站"模型表现"表中的 2.797 / 0.600、1.610 / 0.097 直接来自这里。',
  },
  {
    index: 28,
    cellType: 'markdown',
    section: '12. Combine Food at Home and Food Away from Home',
    title: '三个模型家族的组合方案',
    whatItDoes: '定义三个保持分离的家族：Primary（Home baseline + 原全体员工工资模型）、Long-history（换成一线员工工资）、Survey sensitivity（两个 survey-expanded 模型）。历史组合与官方 Total Food CPI 对照。',
    whyNeeded: '明确"谁是主预测"：Primary 因两个输入都是全国性且直连食品通道而担任 main point forecast。',
  },
  {
    index: 29,
    cellType: 'code',
    section: '12. Combine Food at Home and Food Away from Home',
    title: '按权重合并两个分项的历史回测',
    code: 'def combine_component_backtests(home_backtest, away_backtest, total_actual, family):\n    merged = home_backtest.merge(away_backtest, on=["Forecast_origin", "Target_month", "Horizon_months"], ...)\n    result["Forecast"] = HOME_WEIGHT_INSIDE_FOOD * Forecast_home + AWAY_WEIGHT_INSIDE_FOOD * Forecast_away\n    result["Actual"] = result["Target_month"].map(total_actual)\n    ...',
    outputSummary: 'Total Food OOS 汇总：Primary 12M RMSE 2.035 / OOS R² 0.598；Long-history 2.051 / 0.592；Survey 1.935 / 0.636（All horizons 一并给出）。',
    whatItDoes: '把 Home 与 Away 的逐 origin 预测按 0.609/0.391 权重合并成 Total Food 预测，与官方 Total Food CPI 对比并计算三家族的 OOS 指标。',
    whyNeeded: 'Pacific Life 需要的是 Total Food 的表现；组件好不等于组合好，必须直接验证组合。',
    inputs: 'final_test_backtests + food_total_cpi + 权重',
    outputs: 'primary/long_history/survey_food_oos + total_food_oos_summary',
    ifBroken: '权重写反（0.391/0.609），Total Food 预测系统性偏向 Away，历史对比立刻恶化。',
    linkToForecast: '0.598 与 2.035——会议上最常被追问的两个数字——诞生于此。',
  },
  {
    index: 30,
    cellType: 'markdown',
    section: '12. Combine Food at Home and Food Away from Home',
    title: '12.1 分 horizon 的精度',
    whatItDoes: '引出下一格：按预测期限 1–12 个月分别看 RMSE。',
    whyNeeded: '不同期限的误差特征完全不同，单一数字会掩盖它。',
  },
  {
    index: 31,
    cellType: 'code',
    section: '12. Combine Food at Home and Food Away from Home',
    title: '按 horizon 计算并绘制 OOS RMSE',
    code: 'total_horizon_metrics = pd.concat([\n    metrics_by_horizon(primary_food_oos, "Primary baseline"),\n    metrics_by_horizon(survey_food_oos, "Survey sensitivity"),\n])\nplt.plot(group["Horizon_months"], group["OOS_RMSE"], marker="o", ...)',
    outputSummary: 'Primary RMSE 从 h1 的 1.576 降到 h4 的 1.231 再升到 h12 的 2.035；OOS R² 在 h1 为 −13.5（短期打不过 no-change），h8 附近最高 0.641。',
    whatItDoes: '对两家族按 horizon 1–12 分组计算 RMSE/OOS R² 并画对比曲线。',
    whyNeeded: '揭示重要事实：极短期 no-change 几乎无法战胜（通胀有惯性），模型的价值在中长期——这正是 12 个月预测任务的合理性。',
    inputs: 'primary_food_oos / survey_food_oos',
    outputs: 'total_horizon_metrics 表 + 曲线图',
    linkToForecast: '网站 horizonRmse 图与 Module 11 的"h1 OOS R² 为负"讨论都出自这里。',
  },
  {
    index: 32,
    cellType: 'markdown',
    section: '12. Combine Food at Home and Food Away from Home',
    title: '12.2 历史 12 个月预测 vs 实际',
    whatItDoes: '引出下一格的历史对照图。',
    whyNeeded: '数字之外，让人"看见"模型历史上跟得多紧、什么时候跟丢。',
  },
  {
    index: 33,
    cellType: 'code',
    section: '12. Combine Food at Home and Food Away from Home',
    title: '画历史 12M 预测对照图',
    code: 'plt.plot(plot_primary["Target_month"], plot_primary["Actual"], label="Official Total Food CPI YoY")\nplt.plot(plot_primary["Target_month"], plot_primary["Forecast"], label="Primary baseline 12M forecast")\nplt.plot(plot_survey["Target_month"], plot_survey["Forecast"], label="Survey sensitivity 12M forecast")',
    outputSummary: '2017–2026 年官方 Total Food YoY（黑线）与两家族 12 个月前瞻预测的对照图：2021–22 通胀飙升期模型明显滞后，其余时期贴合较好。',
    whatItDoes: '把 12-month-ahead 的历史预测与实际画在一起。',
    whyNeeded: '直观展示 RMSE 2.035 pp 的含义：大部分时间贴得近，急转弯时会跟丢——这就是预测区间必须存在的原因。',
    inputs: 'primary_food_oos / survey_food_oos（Horizon=12）',
    outputs: 'matplotlib 图',
  },
  {
    index: 34,
    cellType: 'markdown',
    section: '13. Produce the current 12-month forecast',
    title: '当前预测的原则：audit 每个输入',
    whatItDoes: '声明最新共同目标月是 2026-06；每个 predictor 用其最新可得观测；audit 表回答"每个预测月究竟由什么数据产生"。',
    whyNeeded: '这是对"12 个月是不是同一个数复制 12 次"这类问题的制度性回答。',
  },
  {
    index: 35,
    cellType: 'code',
    section: '13. Produce the current 12-month forecast',
    title: '生成当前预测、系数表、方程与 72 行 audit',
    code: 'current_origin = latest_target_month  # 2026-06\ninformation_cutoffs = {p: model_data[p].dropna().index.max() for p in model_data.columns}\nfor name in ["Home baseline", "Away legacy all-employee", "Home survey expanded", "Away survey expanded"]:\n    forecast, audit, coefficients = forecast_from_origin(model_data, name, model_specs[name],\n        current_origin, horizon=12, information_cutoffs=...)',
    outputSummary: '系数表：Home baseline α=1.408 (SE 0.187)、β=0.650 (SE 0.043)，N=881；Away legacy α=1.753、β=0.485，N=219。audit 共 72 行：Home 仅 h1 Observed（1.6294），h2–12 用 1.8790 假设；Away 12 行全部 Observed。',
    whatItDoes: '以 2026-06 为 origin，对 4 个当前模型各生成 12 个月预测 + 完整输入 audit + 系数表，并拼出可读方程文本。',
    whyNeeded: '当前方程（1.408 + 0.650×PPI）与"哪个月用了哪个数"的逐行证据都在这里产生——是会议答辩的弹药库。',
    inputs: 'model_data + 冻结规格 + 各 predictor 的最新观测日期',
    outputs: 'current_component_forecasts / forecast_input_audit / current_coefficient_table / current_equations',
    ifBroken: 'information_cutoffs 若全部设成 origin（忽略调查已出的 7 月值），survey 模型的 h1 输入会退化为假设值。',
    linkToForecast: '网站 Forecast Input Audit 互动表就是这 72 行的复刻。',
  },
  {
    index: 36,
    cellType: 'markdown',
    section: '13. Produce the current 12-month forecast',
    title: '13.1 主预测与调查敏感性的关系',
    whatItDoes: '重申：primary baseline 是 main point estimate；survey 模型作为敏感性范围展示，因为企业价格意向波动大且调查非全国食品专属。',
    whyNeeded: '在数字出现之前先钉牢解释框架，防止 4.34% 喧宾夺主。',
  },
  {
    index: 37,
    cellType: 'code',
    section: '13. Produce the current 12-month forecast',
    title: '合并当前预测 + 经验区间 + Latest Actual',
    code: 'primary_current_forecast = combine_current_forecasts(cc["Home baseline"], cc["Away legacy all-employee"], "Primary baseline")\nerror_quantiles = primary_errors.groupby("Horizon_months")["Forecast_error"].quantile([0.025, 0.975])\nprimary_current_forecast["empirical_lower_95"] = food_yoy + error_q025\n...',
    outputSummary: 'Primary 表：2026-07 总 2.824 → 2027-06 总 3.021（贡献 0.406 pp），经验区间 h12 为 [−0.558, 8.227]；Survey 表：2027-06 总 4.343。Latest Actual：2026-06 总 2.987 / 贡献 0.402。',
    whatItDoes: '把两个分项的当前预测按权重合并成 Primary 与 Survey 两张月度表；用历史 OOS 误差分位数给 Primary 叠加经验 95% 区间；附上 2026-06 的实际值作对照行。',
    whyNeeded: '产出最终交付的数字矩阵：逐月 Home/Away/Total/贡献 + 不确定性区间。',
    inputs: 'current_component_forecasts + primary_food_oos 的历史误差',
    outputs: 'full_primary_forecast / survey_current_forecast',
    linkToForecast: '3.02%（Primary h12）与 4.34%（Survey h12）正式成型于此。',
  },
  {
    index: 38,
    cellType: 'markdown',
    section: '13. Produce the current 12-month forecast',
    title: '13.2 当前预测图',
    whatItDoes: '引出下一格的预测扇形图。',
    whyNeeded: '把数字变成可以放进 PPT 的图。',
  },
  {
    index: 39,
    cellType: 'code',
    section: '13. Produce the current 12-month forecast',
    title: '画当前 12 个月预测图（含区间）',
    code: 'plt.plot(actual_history.index, actual_history, label="Official Total Food CPI YoY")\nplt.plot(full_primary_forecast["date"], full_primary_forecast["food_yoy"], marker="o", linestyle="--", label="Primary baseline")\nplt.fill_between(dates, empirical_lower_95, empirical_upper_95, alpha=0.15)',
    outputSummary: '2017 年以来的官方 Total Food YoY + Primary 虚线 + Survey 点线 + 经验区间阴影，灰色竖线标出 Latest actual（2026-06）。',
    whatItDoes: '把历史实际、Primary 预测、Survey 情景与经验区间画进一张图。',
    whyNeeded: '一图讲清三件事：现在在哪（2.99%）、主预测去哪（3.02%）、不确定性多大（区间很宽）。',
    inputs: 'full_primary_forecast / survey_current_forecast / 历史序列',
    outputs: 'matplotlib 图',
    linkToForecast: '网站 forecastFan 图就是它的交互版。',
  },
  {
    index: 40,
    cellType: 'markdown',
    section: '14. Final results and interpretation',
    title: '结果解读原则',
    whatItDoes: '说明为什么同时报告两个数字：Primary 更易经济学辩护；Survey 回答"如果价格意向传导会怎样"。并给出 OOS R² 的标准解释（相对 no-change 的平方误差改善）。',
    whyNeeded: '这一段就是会议话术的官方版本——网站 Mock Meeting 的参考答案与它对齐。',
  },
  {
    index: 41,
    cellType: 'code',
    section: '14. Final results and interpretation',
    title: '汇总表现表与 PPT 摘要',
    code: 'model_performance = pd.DataFrame([\n  {"Component": "Food at Home", "Model": "Home baseline", **primary_home_12m},\n  {"Component": "Food Away from Home", "Model": "Away legacy all-employee", **primary_away_12m},\n  {"Component": "Official Total Food CPI", "Model": "Primary baseline", **primary_total_12m},\n  {"Component": "Official Total Food CPI", "Model": "Survey sensitivity", **survey_total_12m},\n])\nppt_summary = ...  # Latest / +3M / +6M / +12M',
    outputSummary: '表现表：2.797/0.600、1.610/0.097、2.035/0.598、1.935/0.636。PPT 摘要：Latest 2.70/3.37/2.99/0.40；+3M 与 +6M 均 2.63/3.55/2.99/0.40；+12M 2.63/3.63/3.02/0.41。打印：Primary 12M 3.02%、Survey 4.34%。',
    whatItDoes: '把 12-month-ahead 的四行核心表现与四行 PPT 摘要（Latest/+3/+6/+12）整理成最终交付表，并打印关键数字。',
    whyNeeded: '这是放进汇报页的最终数字——网站"必须使用的当前结果"全部与此一致。',
    inputs: '此前所有回测与当前预测',
    outputs: 'model_performance / ppt_summary + 5 行 print',
    linkToForecast: '"Primary 12-month-ahead forecast: 3.02%" 的原始出处。',
  },
  {
    index: 42,
    cellType: 'markdown',
    section: '15. Limitations',
    title: '六大限制',
    whatItDoes: '列出六项限制：1) 伪实时回测（修订后 FRED 数据，非 ALFRED vintage）；2) 未重建历史发布日；3) 未观察 predictor 用 3 个月平均（后期月份是基准情景）；4) 历史组合用当前权重；5) 调查是区域性、非食品专属；6) 重叠 12 个月误差序列相关（HAC SE + 经验区间应对）。',
    whyNeeded: '诚实的边界声明——它们不否定模型，而是告诉使用者结果应该怎么用。',
    linkToForecast: '限制 3 直接解释了为什么 2026-08 之后的 Home 预测是"基准情景"。',
  },
  {
    index: 43,
    cellType: 'markdown',
    section: '16. Save the reproducible analysis package',
    title: '导出说明',
    whatItDoes: '说明此 cell 会刷新备份 CSV，并把已执行的结果表写成审计包；Food_CPI_Output.xlsx 由同一批表格生成。',
    whyNeeded: '让"网站/Excel 上的每个数字都能追溯到 Notebook"成为可执行的事实。',
  },
  {
    index: 44,
    cellType: 'code',
    section: '16. Save the reproducible analysis package',
    title: '写出 26 张结果表与数据备份',
    code: 'data.to_csv(BACKUP_CSV, encoding="utf-8-sig", date_format="%Y-%m-%d")\nexport_tables = {"data_dictionary": series_metadata, "lag_selection_home": home_best_lags,\n  "final_test_comparison": final_test_comparison, "forecast_input_audit": forecast_input_audit,\n  "total_food_current_primary": full_primary_forecast, "ppt_summary": ppt_summary, ...}\nfor key, frame in export_tables.items():\n    frame.to_json(results_dir / f"{key}.json", orient="split", ...)',
    outputSummary: 'Saved 26 verified result tables to tmp/food_cpi_results；Refreshed Food_CPI_Data.csv。',
    whatItDoes: '刷新 Food_CPI_Data.csv 备份；把 26 张结果表（数据字典、lag 选择、验证/测试对比、audit、当前预测、PPT 摘要等）导出为 JSON 并写 manifest。',
    whyNeeded: '可复现交付：Excel 输出与本课程网站的数据文件都来自这批经过执行验证的表。',
    inputs: '全文所有结果对象',
    outputs: '26 个 JSON + 刷新的 CSV + manifest',
    ifBroken: '若跳过此 cell，下游的 Excel/网站将无法与最新 Notebook 运行保持同步。',
    linkToForecast: '网站 src/data/modelResults.ts 的每个数值都可在这些导出表中找到。',
  },
]
